#! /usr/bin/env bash

_has_command() { command -v "${1}" >/dev/null; }

alias g=git

alias cdtmp='cd "$(mktemp -d)"'
cheat() { curl -s "https://cheat.sh/${1}" | less -R; }

# shellcheck disable=SC2164
mkcd() { mkdir -p "${1}" && cd "${1}"; }


# ╔════════════════════════════════════════════════════════════════════════╗
# ║ Overriding aliases: (Danger zone)                                      ║
# ╚════════════════════════════════════════════════════════════════════════╝

if _has_command 'bat'; then
    alias cat=bat
fi

if _has_command 'eza'; then
    alias ls=eza
fi
